# SPDX-FileCopyrightText: 2021 Rosa Richter
#
# SPDX-License-Identifier: CC0-1.0

version: 2
updates:
- package-ecosystem: mix
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
