# SPDX-FileCopyrightText: 2024 Rosa Richter
#
# SPDX-License-Identifier: AGPL-3.0-or-later

name: Dependency check

on:
  schedule:
    - cron: "0 0 * * *"
  push:
  pull_request:

jobs:
  test-unlocked:
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: 1

    strategy:
      matrix:
        include:
        - elixir-version: 1.17
          otp-version: 27
        - elixir-version: 1.17
          otp-version: 26
        - elixir-version: 1.17
          otp-version: 25
        - elixir-version: 1.16
          otp-version: 26
        - elixir-version: 1.16
          otp-version: 25
        - elixir-version: 1.16
          otp-version: 24

    steps:
    - uses: actions/checkout@v4
    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: ${{ matrix.elixir-version }}
        otp-version: ${{ matrix.otp-version }}
    - name: Restore dependencies cache
      uses: actions/cache@v4
      with:
        path: deps
        key: ${{ runner.os }}-elixir-${{ matrix.elixir-version}}-otp-${{ matrix.otp-version }}-mix-unlocked
    - name: Install unlocked dependencies
      run: |
        mix deps.unlock --all
        mix deps.get
    - name: Run tests
      run: mix test
